'use strict';
export const sep = '/';
export const tools: any = {
  items: [
    'Bold',
    'Italic',
    'Underline',
    'StrikeThrough',
    'SuperScript',
    'SubScript',
    '|',
    'FontName',
    'FontSize',
    'FontColor',
    'BackgroundColor',
    '|',
    'LowerCase',
    'UpperCase',
    '|',
    'Formats',
    'Alignments',
    '|',
    'NumberFormatList',
    'BulletFormatList',
    '|',
    'Outdent',
    'Indent',
    '|',
    'CreateLink',
    'Image',
    'FileManager',
    'Video',
    'Audio',
    'CreateTable',
    '|',
    'FormatPainter',
    'ClearFormat',
    '|',
    'EmojiPicker',
    'Print',
    '|',
    'SourceCode',
    'FullScreen',
    '|',
    'Undo',
    'Redo',
  ],
};
export const toolsMenu: any = {
  items: [
    'FileManager',
    'Image',
    'CreateLink',
    'Video',
    'Audio',
    'CreateTable',
    '|',
    'Bold',
    'Italic',
    'Underline',
    'StrikeThrough',
    'SuperScript',
    'SubScript',
    '|',
    'FontName',
    'FontSize',
    'FontColor',
    'BackgroundColor',
    '|',
    'LowerCase',
    'UpperCase',
    '|',
    'Formats',
    'Alignments',
    '|',
    'NumberFormatList',
    'BulletFormatList',
    '|',
    'Outdent',
    'Indent',
    '|',
    'FormatPainter',
    'ClearFormat',
    '|',
    'EmojiPicker',
    'Print',
    '|',
    'SourceCode',
    'FullScreen',
    '|',
    'Undo',
    'Redo',
  ],
};
export const source: string = 'da';

export const menuItems: any = [
  {
    text: 'Copy Text Selected',
    iconCss: 'fas bi-cursor-text',
  },
  {
    separator: true,
  },
  {
    text: 'New Tab',
    iconCss: 'fas fa-plus',
  },
  {
    text: 'Save',
    iconCss: 'fas fa-save',
  },
  {
    text: 'Update',
    iconCss: 'fas fa-check-circle',
  },
  {
    separator: true,
  },
  {
    text: 'Retrieve',
    iconCss: 'fa fa-cloud-arrow-down',
  },
  {
    separator: true,
  },
  {
    text: 'Copy Quote',
    iconCss: 'fas fa-copy',
  },
  {
    text: 'Paste Quote',
    iconCss: 'fas fa-paste',
  },
  {
    text: 'Cancel Quote Copy',
    iconCss: 'fas fa-ban',
  },
];
export const infoDefault: any = {
  _id: null,
  roundOption: {},
  Direct: false,
  begindate: new Date(),
  enddate: new Date(),
  quoteValidity: new Date(new Date().setDate(new Date().getDate() + 14)),
  TranferTimeFrom: '',
  TranferTimeTo: '',
  PickupTime: new Date(2029, 1, 1, 0, 0, 0, 0),
  stickyNotes: {
    note: '',
  },
  optionTripleShare: 'TripleReduction',
  isoReps: [],
  IshaveTransfer: false,
  Items_Calculator: [],
  MarkupAllLanding: 20,
  codeVersion: 1,
  MarkupAllHotel: 10,
  periodSEASONAL: false,
  periodDAILY: true,
  splitByAcc: false,
  UngroupAcc: false,
  PaxMax: 35,
  Proposalstatus: 'NEW',
  market: ['WW'],
  ageny: [''],
  noteTiers: '* Price Per Person',
  CRM: false,
  DMK: true,
  priceSIC: 0,
  paxBreakOperator: 0,
  Items_DirectMarkup: [],
  lsExtra: [],
  periods: [],
  Items_ChildPolicy: [],
  cancelation_policy: [],
  depositPolicies: [],
  lsPeriod: [],
  lsTiming: [],
  timeView: '0h00',
  TotalDuration: 0,
  timepicker: new Date(new Date().setHours(8, 0, 0, 0)),
  startTime: { hour: 8, minute: 0, second: 0 },
  duration: [],
  tourStyle: [],
  availab: {
    sun: true,
    mon: true,
    tue: true,
    wed: true,
    thu: true,
    fri: true,
    sat: true,
  },
  maps: [],
  imageMaps: '',
  numbertourLeader: 0,
  tourLeaderPaxRange: 0,
  ObjectDemandSellingPrice: { paxBreak: [] },
  GridFooterTotalTour: [],
  sumRefundPaid: 0,
};

export const userDocumentURI =
  'https://docs.google.com/document/d/e/2PACX-1vQb7zODN7qPUj3BHcHRg1ysAHSlfEK96RgqfX_1Y-foAdWi8-5rqskzdCPhf2nZxLnOBUmjtzWAdatq/pub';
export const _ismarkup: any = {
  price: 300,
  value: [
    { mk: 10, value: 7 },
    { mk: 8, value: 6 },
    { mk: 7, value: 5 },
    { mk: 5, value: 5 },
  ],
};
export const ckeditConfig: any = {
  versionCheck: false,
  toolbar: [
    {
      name: 'document',
      items: ['Source', '-', 'Save', 'NewPage', 'ExportPdf', 'Preview', 'Print', '-', 'Templates'],
    },
    {
      name: 'clipboard',
      items: ['Cut', 'Copy', 'Paste', 'PasteText', 'PasteFromWord', '-', 'Undo', 'Redo'],
    },
    {
      name: 'editing',
      items: ['Find', 'Replace', '-', 'SelectAll', '-', 'Scayt'],
    },
    {
      name: 'forms',
      items: ['Form', 'Checkbox', 'Radio', 'TextField', 'Textarea', 'Select', 'Button', 'ImageButton', 'HiddenField'],
    },
    {
      name: 'basicstyles',
      items: [
        'Bold',
        'Italic',
        'Underline',
        'Strike',
        'Subscript',
        'Superscript',
        '-',
        'CopyFormatting',
        'RemoveFormat',
      ],
    },
    {
      name: 'paragraph',
      items: [
        'NumberedList',
        'BulletedList',
        '-',
        'Outdent',
        'Indent',
        '-',
        'Blockquote',
        'CreateDiv',
        '-',
        'JustifyLeft',
        'JustifyCenter',
        'JustifyRight',
        'JustifyBlock',
        '-',
        'BidiLtr',
        'BidiRtl',
        'Language',
      ],
    },
    { name: 'links', items: ['Link', 'Unlink', 'Anchor'] },
    {
      name: 'insert',
      items: ['Image', 'Flash', 'Table', 'HorizontalRule', 'Smiley', 'SpecialChar', 'PageBreak', 'Iframe'],
    },
    { name: 'styles', items: ['Styles', 'Format', 'Font', 'FontSize'] },
    { name: 'colors', items: ['TextColor', 'BGColor'] },
    { name: 'tools', items: ['Maximize', 'ShowBlocks'] },
    { name: 'about', items: ['About'] },
  ],
  height: 400,
  buttons: 'Link,Unlink,Image',
  widgets: 'image',
  fullPage: false,
  allowedContent: true,
  enterMode: 2,
  colorButton_colors: '5A5A5A,BEBEBF,454545,FFF,DDD,CCEAEE,66AB16',
  colorButton_enableAutomatic: false,
};
export const ckeditConfigComment: any = {
  versionCheck: false,
  toolbar: [
    {
      name: 'basicstyles',
      items: ['Bold', 'Italic', 'Underline', 'Strike', 'RemoveFormat'],
    },
    {
      name: 'paragraph',
      items: ['NumberedList', 'BulletedList', '-', 'Outdent', 'Indent', '-', 'Blockquote'],
    },
    { name: 'links', items: ['Link', 'Unlink'] },
  ],
  height: 200,
  buttons: 'Link,Unlink',
  widgets: 'image',
  fullPage: false,
  allowedContent: true,
  enterMode: 2,
  colorButton_colors: '5A5A5A,BEBEBF,454545,FFF,DDD,CCEAEE,66AB16',
  colorButton_enableAutomatic: false,
};
export const surveyTypes: any = [
  { _id: 'Exercise', value: 'Exercise' },
  { _id: 'Assignment', value: 'Assignment' },
  { _id: 'Personal Assignment', value: 'Personal Assignment' },
];
export const lsCategory: any = [
  { id: 'Travel', value: 'Travel' },
  { id: 'Hospitality', value: 'Hospitality' },
  { id: 'Event', value: 'Event' },
];
export const familyFonts = {
  width: '90px',
  items: [
    {
      text: 'Arial',
      value: 'Arial,Helvetica,sans-serif',
      cssClass: 'e-arial',
    },
    {
      text: 'Book Antiqua',
      value: 'Book Antiqua',
    },
    {
      text: 'Be Vietnam',
      value: 'Be Vietnam',
    },
    {
      text: 'Calibri',
      value: 'Calibri',
      cssClass: 'e-Calibri',
    },
    {
      text: 'Coiny',
      value: 'Coiny',
      cssClass: 'e-Coiny',
    },
    {
      text: 'Garamond',
      value: 'Garamond',
    },
    { text: 'Georgia', value: 'Georgia,serif', cssClass: 'e-georgia' },
    {
      text: 'Pacifico',
      value: 'Pacifico',
    },
    {
      text: 'Roboto',
      value: 'Roboto',
    },
    { text: 'Segoe UI', value: 'Segoe UI', cssClass: 'e-segoe-ui' },
    {
      text: 'Varela Round',
      value: 'Varela Round',
    },
    {
      text: 'Impact',
      value: 'Impact,Charcoal,sans-serif',
      cssClass: 'e-impact',
    },
  ],
};
export const tourMenuLeft: any = [
  {
    id: '0',
    name: 'BOOKING',
    hasChild: true,
    selected: false,
    expanded: true,
    show: true,
    icon: 'bi bi-box-seam-fill',
  },
  { id: '1', pid: '0', name: 'INFORMATION', selected: true, show: true, icon: 'bi bi-cloud-haze2' },
  { id: '21', pid: '0', name: 'THUMBNAIL', selected: false, show: true, icon: 'bi bi-image-alt' },
  { id: '2', pid: '0', name: 'PAX BREAK', selected: false, show: true, icon: 'bi bi-people' },
  { id: '3', pid: '0', name: 'BUY PRICE', selected: false, show: true, icon: 'bi bi-basket2' },
  { id: '4', pid: '0', name: 'SELL PRICE', selected: false, show: true, icon: 'bi bi-currency-exchange' },
  { id: '34', pid: '0', name: 'By Service Type', selected: false, show: true, icon: 'bi bi-funnel' },
  { id: '32', pid: '0', name: 'EXCEL Comparison', selected: false, show: true, icon: 'bi bi-table' },
  { id: '33', pid: '0', name: 'AUDIT LOGS', selected: false, show: true, icon: 'bi bi-clock-history' },
  { id: '5', pid: '0', name: 'CHILD POLICY', selected: false, show: true, icon: 'bi bi-person-exclamation' },
  { id: '55', pid: '0', name: 'CANCELATION POLICY', selected: false, show: true, icon: 'bi bi-recycle' },
  { id: '555', pid: '0', name: 'DEPOSIT POLICY', selected: false, show: true, icon: 'bi bi-calendar-range' },
  { id: '6', pid: '0', name: 'SURCHARGE', selected: false, show: true, icon: 'bi bi-infinity' },
  { id: '7', pid: '0', name: 'PRICE (Direct MK)', selected: false, show: true, icon: 'bi bi-layers-fill' },
  { id: '8', pid: '0', name: 'PAX MANAGEMENT', selected: false, show: true, icon: 'bi bi-person-vcard' },
  { id: '9', pid: '0', name: 'EXCEL (Total Sell)', selected: false, show: true, icon: 'bi bi-file-earmark-excel' },
  { id: '31', pid: '0', name: 'EXCEL (Pax Manifest)', selected: false, show: true, icon: 'bi bi-people-fill' },
  { id: '10', pid: '0', name: 'INVOICE', selected: false, show: true, icon: 'bi bi-file-earmark-excel' },
  { id: '17', pid: '0', name: 'PAYMENT PROCESS (AR)', selected: false, show: true, icon: 'bi bi-mailbox' },
  { id: '11', pid: '0', name: 'DESCRIPTION', selected: false, show: true, icon: 'bi bi-file-earmark-word' },
  { id: '20', pid: '0', name: 'INCLUDING - EXCLUDING', selected: false, show: true, icon: 'bi bi-file-earmark-word' },
  { id: '13', pid: '0', name: 'NOTE', selected: false, show: true, icon: 'bi bi-body-text' },
  { id: '14', pid: '0', name: 'TIMING', selected: false, show: true, icon: 'bi bi-clock' },
  { id: '15', pid: '0', name: 'MAP CREATOR', selected: false, show: true, icon: 'bi bi-map' },
  // End Booking
  { id: '16', name: 'OPERATION', hasChild: false, selected: false, show: true, icon: 'bi bi-bar-chart-line' },
  { id: '18', name: 'CMS', hasChild: false, selected: false, show: true, icon: 'bi bi-database' },
  { id: '19', name: 'BOOKING SUMMARY', hasChild: false, selected: false, show: true, icon: 'bi bi-columns-gap' },
  { id: '22', name: 'Logs', hasChild: false, selected: false, show: true, icon: 'bi bi-save2' },
  { id: '24', name: 'Optional Booking', hasChild: false, selected: false, show: true, icon: 'bi bi-save2' },
];
export const ls_status: any = [
  { value: 'NEW', name: 'New Request' },
  { value: 'Amend', name: 'Amend' },
  { value: 'Blocking', name: 'Blocking / New Booking' },
  // { value: 'NewBooking', name: 'New Booking' },
  { value: 'CONFIRMED', name: 'Confirmed' },
  // { value: 'CONFIRMED with Amendments', name: 'Confirmed with Amendments' },
  { value: 'ProposalClosed', name: 'Proposal Closed' },
  { value: 'CANCELLED without Charge', name: 'Cancelled' },
  { value: 'CANCELLED with Charge', name: 'Cancelled with Charge' },
  { value: 'Completed', name: 'Completed' },
  { value: 'CLOSED', name: 'CLOSED' },
];
export const defaultTiers: any = [
  {
    id: 0,
    maxPax: 25,
    name: '8 PAX BREAKS',
    value: [
      { pax: 1, markUp: 0, number: 0, price: 0, priceby: 0, profit: 0, margin: 0 },
      { pax: 2, markUp: 0, number: 1, price: 0, priceby: 0, profit: 0, margin: 0 },
      { pax: 3, markUp: 0, number: 2, price: 0, priceby: 0, profit: 0, margin: 0 },
      { pax: 7, markUp: 0, number: 3, price: 0, priceby: 0, profit: 0, margin: 0 },
      { pax: 10, markUp: 0, number: 4, price: 0, priceby: 0, profit: 0, margin: 0 },
      { pax: 15, markUp: 0, number: 5, price: 0, priceby: 0, profit: 0, margin: 0 },
      { pax: 20, markUp: 0, number: 6, price: 0, priceby: 0, profit: 0, margin: 0 },
      { pax: 25, markUp: 0, number: 7, price: 0, priceby: 0, profit: 0, margin: 0 },
    ],
  },
  {
    id: 1,
    maxPax: 30,
    name: '9 PAX BREAKS',
    value: [
      { pax: 1, markUp: 0, number: 0, price: 0, priceby: 0, profit: 0, margin: 0 },
      { pax: 2, markUp: 0, number: 1, price: 0, priceby: 0, profit: 0, margin: 0 },
      { pax: 3, markUp: 0, number: 2, price: 0, priceby: 0, profit: 0, margin: 0 },
      { pax: 7, markUp: 0, number: 3, price: 0, priceby: 0, profit: 0, margin: 0 },
      { pax: 10, markUp: 0, number: 4, price: 0, priceby: 0, profit: 0, margin: 0 },
      { pax: 15, markUp: 0, number: 5, price: 0, priceby: 0, profit: 0, margin: 0 },
      { pax: 20, markUp: 0, number: 6, price: 0, priceby: 0, profit: 0, margin: 0 },
      { pax: 25, markUp: 0, number: 7, price: 0, priceby: 0, profit: 0, margin: 0 },
      { pax: 30, markUp: 0, number: 8, price: 0, priceby: 0, profit: 0, margin: 0 },
    ],
  },
  {
    id: 2,
    maxPax: 35,
    name: '10 PAX BREAKS',
    value: [
      { pax: 1, markUp: 0, number: 0, price: 0, priceby: 0, profit: 0, margin: 0 },
      { pax: 3, markUp: 0, number: 1, price: 0, priceby: 0, profit: 0, margin: 0 },
      { pax: 5, markUp: 0, number: 2, price: 0, priceby: 0, profit: 0, margin: 0 },
      { pax: 7, markUp: 0, number: 3, price: 0, priceby: 0, profit: 0, margin: 0 },
      { pax: 10, markUp: 0, number: 4, price: 0, priceby: 0, profit: 0, margin: 0 },
      { pax: 15, markUp: 0, number: 5, price: 0, priceby: 0, profit: 0, margin: 0 },
      { pax: 20, markUp: 0, number: 6, price: 0, priceby: 0, profit: 0, margin: 0 },
      { pax: 25, markUp: 0, number: 7, price: 0, priceby: 0, profit: 0, margin: 0 },
      { pax: 30, markUp: 0, number: 8, price: 0, priceby: 0, profit: 0, margin: 0 },
      { pax: 35, markUp: 0, number: 9, price: 0, priceby: 0, profit: 0, margin: 0 },
    ],
  },
];

export const items_RoomOccupancy: any = [
  {
    name: '1 Bed / Twin bed room',
    options: [
      {
        extraBed: false,
        noExtraBed: 0,
        occA: 2,
        occC: 1,
        childs: [{ num: 1, from: 1, to: 6 }],
      },
      {
        extraBed: true,
        noExtraBed: 1,
        occA: 2,
        occC: 2,
        childs: [
          { num: 1, from: 1, to: 6 },
          { num: 2, from: 1, to: 12 },
        ],
      },
      { extraBed: true, noExtraBed: 1, occA: 3, occC: 0, childs: [] },
    ],
  },
  {
    name: '2 bed Room',
    options: [
      {
        extraBed: false,
        noExtraBed: 0,
        occA: 4,
        occC: 2,
        childs: [
          { num: 1, from: 1, to: 6 },
          { num: 2, from: 1, to: 6 },
        ],
      },
      {
        extraBed: true,
        noExtraBed: 2,
        occA: 4,
        occC: 4,
        childs: [
          { num: 1, from: 1, to: 6 },
          { num: 2, from: 1, to: 12 },
          { num: 3, from: 1, to: 6 },
          { num: 4, from: 1, to: 12 },
        ],
      },
      { extraBed: true, noExtraBed: 2, occA: 6, occC: 0, childs: [] },
    ],
  },
  {
    name: '3 Bed Room',
    options: [
      {
        extraBed: false,
        noExtraBed: 0,
        occA: 6,
        occC: 3,
        childs: [
          { num: 1, from: 1, to: 6 },
          { num: 2, from: 1, to: 6 },
          { num: 3, from: 1, to: 6 },
        ],
      },
      {
        extraBed: true,
        noExtraBed: 3,
        occA: 6,
        occC: 6,
        childs: [
          { num: 1, from: 1, to: 6 },
          { num: 2, from: 1, to: 6 },
          { num: 3, from: 1, to: 6 },
          { num: 4, from: 1, to: 12 },
          { num: 5, from: 1, to: 12 },
          { num: 6, from: 1, to: 12 },
        ],
      },
      { extraBed: true, noExtraBed: 3, occA: 9, occC: 0, childs: [] },
    ],
  },
  {
    name: '4 Bed Room',
    options: [
      {
        extraBed: false,
        noExtraBed: 0,
        occA: 8,
        occC: 4,
        childs: [
          { num: 1, from: 1, to: 6 },
          { num: 2, from: 1, to: 6 },
          { num: 3, from: 1, to: 6 },
          { num: 4, from: 1, to: 6 },
        ],
      },
      {
        extraBed: true,
        noExtraBed: 3,
        occA: 8,
        occC: 8,
        childs: [
          { num: 1, from: 1, to: 6 },
          { num: 2, from: 1, to: 6 },
          { num: 3, from: 1, to: 6 },
          { num: 4, from: 1, to: 6 },
          { num: 5, from: 1, to: 12 },
          { num: 6, from: 1, to: 12 },
          { num: 7, from: 1, to: 12 },
          { num: 8, from: 1, to: 12 },
        ],
      },
      { extraBed: true, noExtraBed: 4, occA: 12, occC: 0, childs: [] },
    ],
  },
  {
    name: '5 Bed Room',
    options: [
      {
        extraBed: false,
        noExtraBed: 0,
        occA: 10,
        occC: 5,
        childs: [
          { num: 1, from: 1, to: 6 },
          { num: 2, from: 1, to: 6 },
          { num: 3, from: 1, to: 6 },
          { num: 4, from: 1, to: 6 },
          { num: 5, from: 1, to: 6 },
        ],
      },
      {
        extraBed: true,
        noExtraBed: 5,
        occA: 10,
        occC: 10,
        childs: [
          { num: 1, from: 1, to: 6 },
          { num: 2, from: 1, to: 6 },
          { num: 3, from: 1, to: 6 },
          { num: 4, from: 1, to: 6 },
          { num: 5, from: 1, to: 6 },
          { num: 6, from: 1, to: 12 },
          { num: 7, from: 1, to: 12 },
          { num: 8, from: 1, to: 12 },
          { num: 9, from: 1, to: 12 },
          { num: 10, from: 1, to: 12 },
        ],
      },
      { extraBed: true, noExtraBed: 5, occA: 15, occC: 0, childs: [] },
    ],
  },
  {
    name: '6 Bed Room',
    options: [
      {
        extraBed: false,
        noExtraBed: 0,
        occA: 12,
        occC: 6,
        childs: [
          { num: 1, from: 1, to: 6 },
          { num: 2, from: 1, to: 6 },
          { num: 3, from: 1, to: 6 },
          { num: 4, from: 1, to: 6 },
          { num: 5, from: 1, to: 6 },
          { num: 6, from: 1, to: 6 },
        ],
      },
      {
        extraBed: true,
        noExtraBed: 6,
        occA: 12,
        occC: 12,
        childs: [
          { num: 1, from: 1, to: 6 },
          { num: 2, from: 1, to: 6 },
          { num: 3, from: 1, to: 6 },
          { num: 4, from: 1, to: 6 },
          { num: 5, from: 1, to: 6 },
          { num: 6, from: 1, to: 12 },
          { num: 7, from: 1, to: 12 },
          { num: 8, from: 1, to: 12 },
          { num: 9, from: 1, to: 12 },
          { num: 10, from: 1, to: 12 },
          { num: 11, from: 1, to: 12 },
          { num: 12, from: 1, to: 12 },
        ],
      },
      { extraBed: true, noExtraBed: 6, occA: 18, occC: 0, childs: [] },
    ],
  },
  {
    name: '7 Bed Room',
    options: [
      {
        extraBed: false,
        noExtraBed: 0,
        occA: 14,
        occC: 7,
        childs: [
          { num: 1, from: 1, to: 6 },
          { num: 2, from: 1, to: 6 },
          { num: 3, from: 1, to: 6 },
          { num: 4, from: 1, to: 6 },
          { num: 5, from: 1, to: 6 },
          { num: 6, from: 1, to: 6 },
          { num: 7, from: 1, to: 6 },
        ],
      },
      {
        extraBed: true,
        noExtraBed: 7,
        occA: 14,
        occC: 14,
        childs: [
          { num: 1, from: 1, to: 6 },
          { num: 2, from: 1, to: 6 },
          { num: 3, from: 1, to: 6 },
          { num: 4, from: 1, to: 6 },
          { num: 5, from: 1, to: 6 },
          { num: 6, from: 1, to: 12 },
          { num: 7, from: 1, to: 12 },
          { num: 8, from: 1, to: 12 },
          { num: 9, from: 1, to: 12 },
          { num: 10, from: 1, to: 12 },
          { num: 11, from: 1, to: 12 },
          { num: 12, from: 1, to: 12 },
          { num: 13, from: 1, to: 12 },
          { num: 14, from: 1, to: 12 },
        ],
      },
      { extraBed: true, noExtraBed: 7, occA: 21, occC: 0, childs: [] },
    ],
  },
  {
    name: '8 Bed Room',
    options: [
      {
        extraBed: false,
        noExtraBed: 0,
        occA: 16,
        occC: 8,
        childs: [
          { num: 1, from: 1, to: 6 },
          { num: 2, from: 1, to: 6 },
          { num: 3, from: 1, to: 6 },
          { num: 4, from: 1, to: 6 },
          { num: 5, from: 1, to: 6 },
          { num: 6, from: 1, to: 6 },
          { num: 7, from: 1, to: 6 },
          { num: 8, from: 1, to: 6 },
        ],
      },
      {
        extraBed: true,
        noExtraBed: 8,
        occA: 16,
        occC: 16,
        childs: [
          { num: 1, from: 1, to: 6 },
          { num: 2, from: 1, to: 6 },
          { num: 3, from: 1, to: 6 },
          { num: 4, from: 1, to: 6 },
          { num: 5, from: 1, to: 6 },
          { num: 6, from: 1, to: 12 },
          { num: 7, from: 1, to: 12 },
          { num: 8, from: 1, to: 12 },
          { num: 9, from: 1, to: 12 },
          { num: 10, from: 1, to: 12 },
          { num: 11, from: 1, to: 12 },
          { num: 12, from: 1, to: 12 },
          { num: 13, from: 1, to: 12 },
          { num: 14, from: 1, to: 12 },
          { num: 15, from: 1, to: 12 },
          { num: 16, from: 1, to: 12 },
        ],
      },
      { extraBed: true, noExtraBed: 8, occA: 24, occC: 0, childs: [] },
    ],
  },
  {
    name: '9 Bed Room',
    options: [
      {
        extraBed: false,
        noExtraBed: 0,
        occA: 18,
        occC: 9,
        childs: [
          { num: 1, from: 1, to: 6 },
          { num: 2, from: 1, to: 6 },
          { num: 3, from: 1, to: 6 },
          { num: 4, from: 1, to: 6 },
          { num: 5, from: 1, to: 6 },
          { num: 6, from: 1, to: 6 },
          { num: 7, from: 1, to: 6 },
          { num: 8, from: 1, to: 6 },
          { num: 9, from: 1, to: 6 },
        ],
      },
      {
        extraBed: true,
        noExtraBed: 9,
        occA: 18,
        occC: 18,
        childs: [
          { num: 1, from: 1, to: 6 },
          { num: 2, from: 1, to: 6 },
          { num: 3, from: 1, to: 6 },
          { num: 4, from: 1, to: 6 },
          { num: 5, from: 1, to: 6 },
          { num: 6, from: 1, to: 12 },
          { num: 7, from: 1, to: 12 },
          { num: 8, from: 1, to: 12 },
          { num: 9, from: 1, to: 12 },
          { num: 10, from: 1, to: 12 },
          { num: 11, from: 1, to: 12 },
          { num: 12, from: 1, to: 12 },
          { num: 13, from: 1, to: 12 },
          { num: 14, from: 1, to: 12 },
          { num: 15, from: 1, to: 12 },
          { num: 16, from: 1, to: 12 },
          { num: 17, from: 1, to: 12 },
          { num: 18, from: 1, to: 12 },
        ],
      },
      { extraBed: true, noExtraBed: 9, occA: 27, occC: 0, childs: [] },
    ],
  },
  {
    name: '10 Bed Room',
    options: [
      {
        extraBed: false,
        noExtraBed: 0,
        occA: 20,
        occC: 10,
        childs: [
          { num: 1, from: 1, to: 6 },
          { num: 2, from: 1, to: 6 },
          { num: 3, from: 1, to: 6 },
          { num: 4, from: 1, to: 6 },
          { num: 5, from: 1, to: 6 },
          { num: 6, from: 1, to: 6 },
          { num: 7, from: 1, to: 6 },
          { num: 8, from: 1, to: 6 },
          { num: 9, from: 1, to: 6 },
          { num: 10, from: 1, to: 6 },
        ],
      },
      {
        extraBed: true,
        noExtraBed: 10,
        occA: 20,
        occC: 20,
        childs: [
          { num: 1, from: 1, to: 6 },
          { num: 2, from: 1, to: 6 },
          { num: 3, from: 1, to: 6 },
          { num: 4, from: 1, to: 6 },
          { num: 5, from: 1, to: 6 },
          { num: 6, from: 1, to: 12 },
          { num: 7, from: 1, to: 12 },
          { num: 8, from: 1, to: 12 },
          { num: 9, from: 1, to: 12 },
          { num: 10, from: 1, to: 12 },
          { num: 11, from: 1, to: 12 },
          { num: 12, from: 1, to: 12 },
          { num: 13, from: 1, to: 12 },
          { num: 14, from: 1, to: 12 },
          { num: 15, from: 1, to: 12 },
          { num: 16, from: 1, to: 12 },
          { num: 17, from: 1, to: 12 },
          { num: 18, from: 1, to: 12 },
          { num: 19, from: 1, to: 12 },
          { num: 20, from: 1, to: 12 },
        ],
      },
      { extraBed: true, noExtraBed: 10, occA: 30, occC: 0, childs: [] },
    ],
  },
  {
    name: '11 Bed Room',
    options: [
      {
        extraBed: false,
        noExtraBed: 0,
        occA: 22,
        occC: 11,
        childs: [
          { num: 1, from: 1, to: 6 },
          { num: 2, from: 1, to: 6 },
          { num: 3, from: 1, to: 6 },
          { num: 4, from: 1, to: 6 },
          { num: 5, from: 1, to: 6 },
          { num: 6, from: 1, to: 6 },
          { num: 7, from: 1, to: 6 },
          { num: 8, from: 1, to: 6 },
          { num: 9, from: 1, to: 6 },
          { num: 10, from: 1, to: 6 },
          { num: 11, from: 1, to: 6 },
        ],
      },
      {
        extraBed: true,
        noExtraBed: 11,
        occA: 22,
        occC: 22,
        childs: [
          { num: 1, from: 1, to: 6 },
          { num: 2, from: 1, to: 6 },
          { num: 3, from: 1, to: 6 },
          { num: 4, from: 1, to: 6 },
          { num: 5, from: 1, to: 6 },
          { num: 6, from: 1, to: 12 },
          { num: 7, from: 1, to: 12 },
          { num: 8, from: 1, to: 12 },
          { num: 9, from: 1, to: 12 },
          { num: 10, from: 1, to: 12 },
          { num: 11, from: 1, to: 12 },
          { num: 12, from: 1, to: 12 },
          { num: 13, from: 1, to: 12 },
          { num: 14, from: 1, to: 12 },
          { num: 15, from: 1, to: 12 },
          { num: 16, from: 1, to: 12 },
          { num: 17, from: 1, to: 12 },
          { num: 18, from: 1, to: 12 },
          { num: 19, from: 1, to: 12 },
          { num: 20, from: 1, to: 12 },
          { num: 21, from: 1, to: 12 },
          { num: 22, from: 1, to: 12 },
        ],
      },
      { extraBed: true, noExtraBed: 11, occA: 33, occC: 0, childs: [] },
    ],
  },
  {
    name: '12 Bed Room',
    options: [
      {
        extraBed: false,
        noExtraBed: 0,
        occA: 24,
        occC: 12,
        childs: [
          { num: 1, from: 1, to: 6 },
          { num: 2, from: 1, to: 6 },
          { num: 3, from: 1, to: 6 },
          { num: 4, from: 1, to: 6 },
          { num: 5, from: 1, to: 6 },
          { num: 6, from: 1, to: 6 },
          { num: 7, from: 1, to: 6 },
          { num: 8, from: 1, to: 6 },
          { num: 9, from: 1, to: 6 },
          { num: 10, from: 1, to: 6 },
          { num: 11, from: 1, to: 6 },
          { num: 12, from: 1, to: 6 },
        ],
      },
      {
        extraBed: true,
        noExtraBed: 12,
        occA: 24,
        occC: 24,
        childs: [
          { num: 1, from: 1, to: 6 },
          { num: 2, from: 1, to: 6 },
          { num: 3, from: 1, to: 6 },
          { num: 4, from: 1, to: 6 },
          { num: 5, from: 1, to: 6 },
          { num: 6, from: 1, to: 12 },
          { num: 7, from: 1, to: 12 },
          { num: 8, from: 1, to: 12 },
          { num: 9, from: 1, to: 12 },
          { num: 10, from: 1, to: 12 },
          { num: 11, from: 1, to: 12 },
          { num: 12, from: 1, to: 12 },
          { num: 13, from: 1, to: 12 },
          { num: 14, from: 1, to: 12 },
          { num: 15, from: 1, to: 12 },
          { num: 16, from: 1, to: 12 },
          { num: 17, from: 1, to: 12 },
          { num: 18, from: 1, to: 12 },
          { num: 19, from: 1, to: 12 },
          { num: 20, from: 1, to: 12 },
          { num: 21, from: 1, to: 12 },
          { num: 22, from: 1, to: 12 },
          { num: 23, from: 1, to: 12 },
          { num: 24, from: 1, to: 12 },
        ],
      },
      { extraBed: true, noExtraBed: 12, occA: 36, occC: 0, childs: [] },
    ],
  },
  {
    name: '13 Bed Room',
    options: [
      {
        extraBed: false,
        noExtraBed: 0,
        occA: 26,
        occC: 13,
        childs: [
          { num: 1, from: 1, to: 6 },
          { num: 2, from: 1, to: 6 },
          { num: 3, from: 1, to: 6 },
          { num: 4, from: 1, to: 6 },
          { num: 5, from: 1, to: 6 },
          { num: 6, from: 1, to: 6 },
          { num: 7, from: 1, to: 6 },
          { num: 8, from: 1, to: 6 },
          { num: 9, from: 1, to: 6 },
          { num: 10, from: 1, to: 6 },
          { num: 11, from: 1, to: 6 },
          { num: 12, from: 1, to: 6 },
          { num: 13, from: 1, to: 6 },
        ],
      },
      {
        extraBed: true,
        noExtraBed: 13,
        occA: 26,
        occC: 26,
        childs: [
          { num: 1, from: 1, to: 6 },
          { num: 2, from: 1, to: 6 },
          { num: 3, from: 1, to: 6 },
          { num: 4, from: 1, to: 6 },
          { num: 5, from: 1, to: 6 },
          { num: 6, from: 1, to: 12 },
          { num: 7, from: 1, to: 12 },
          { num: 8, from: 1, to: 12 },
          { num: 9, from: 1, to: 12 },
          { num: 10, from: 1, to: 12 },
          { num: 11, from: 1, to: 12 },
          { num: 12, from: 1, to: 12 },
          { num: 13, from: 1, to: 12 },
          { num: 14, from: 1, to: 12 },
          { num: 15, from: 1, to: 12 },
          { num: 16, from: 1, to: 12 },
          { num: 17, from: 1, to: 12 },
          { num: 18, from: 1, to: 12 },
          { num: 19, from: 1, to: 12 },
          { num: 20, from: 1, to: 12 },
          { num: 21, from: 1, to: 12 },
          { num: 22, from: 1, to: 12 },
          { num: 23, from: 1, to: 12 },
          { num: 24, from: 1, to: 12 },
          { num: 25, from: 1, to: 12 },
          { num: 26, from: 1, to: 12 },
        ],
      },
      { extraBed: true, noExtraBed: 13, occA: 39, occC: 0, childs: [] },
    ],
  },
  {
    name: '14 Bed Room',
    options: [
      {
        extraBed: false,
        noExtraBed: 0,
        occA: 28,
        occC: 14,
        childs: [
          { num: 1, from: 1, to: 6 },
          { num: 2, from: 1, to: 6 },
          { num: 3, from: 1, to: 6 },
          { num: 4, from: 1, to: 6 },
          { num: 5, from: 1, to: 6 },
          { num: 6, from: 1, to: 6 },
          { num: 7, from: 1, to: 6 },
          { num: 8, from: 1, to: 6 },
          { num: 9, from: 1, to: 6 },
          { num: 10, from: 1, to: 6 },
          { num: 11, from: 1, to: 6 },
          { num: 12, from: 1, to: 6 },
          { num: 13, from: 1, to: 6 },
          { num: 14, from: 1, to: 6 },
        ],
      },
      {
        extraBed: true,
        noExtraBed: 14,
        occA: 28,
        occC: 28,
        childs: [
          { num: 1, from: 1, to: 6 },
          { num: 2, from: 1, to: 6 },
          { num: 3, from: 1, to: 6 },
          { num: 4, from: 1, to: 6 },
          { num: 5, from: 1, to: 6 },
          { num: 6, from: 1, to: 12 },
          { num: 7, from: 1, to: 12 },
          { num: 8, from: 1, to: 12 },
          { num: 9, from: 1, to: 12 },
          { num: 10, from: 1, to: 12 },
          { num: 11, from: 1, to: 12 },
          { num: 12, from: 1, to: 12 },
          { num: 13, from: 1, to: 12 },
          { num: 14, from: 1, to: 12 },
          { num: 15, from: 1, to: 12 },
          { num: 16, from: 1, to: 12 },
          { num: 17, from: 1, to: 12 },
          { num: 18, from: 1, to: 12 },
          { num: 19, from: 1, to: 12 },
          { num: 20, from: 1, to: 12 },
          { num: 21, from: 1, to: 12 },
          { num: 22, from: 1, to: 12 },
          { num: 23, from: 1, to: 12 },
          { num: 24, from: 1, to: 12 },
          { num: 25, from: 1, to: 12 },
          { num: 26, from: 1, to: 12 },
          { num: 27, from: 1, to: 12 },
          { num: 28, from: 1, to: 12 },
        ],
      },
      { extraBed: true, noExtraBed: 14, occA: 42, occC: 0, childs: [] },
    ],
  },
  {
    name: '15 Bed Room',
    options: [
      {
        extraBed: false,
        noExtraBed: 0,
        occA: 30,
        occC: 15,
        childs: [
          { num: 1, from: 1, to: 6 },
          { num: 2, from: 1, to: 6 },
          { num: 3, from: 1, to: 6 },
          { num: 4, from: 1, to: 6 },
          { num: 5, from: 1, to: 6 },
          { num: 6, from: 1, to: 6 },
          { num: 7, from: 1, to: 6 },
          { num: 8, from: 1, to: 6 },
          { num: 9, from: 1, to: 6 },
          { num: 10, from: 1, to: 6 },
          { num: 11, from: 1, to: 6 },
          { num: 12, from: 1, to: 6 },
          { num: 13, from: 1, to: 6 },
          { num: 14, from: 1, to: 6 },
          { num: 15, from: 1, to: 6 },
        ],
      },
      {
        extraBed: true,
        noExtraBed: 15,
        occA: 30,
        occC: 30,
        childs: [
          { num: 1, from: 1, to: 6 },
          { num: 2, from: 1, to: 6 },
          { num: 3, from: 1, to: 6 },
          { num: 4, from: 1, to: 6 },
          { num: 5, from: 1, to: 6 },
          { num: 6, from: 1, to: 12 },
          { num: 7, from: 1, to: 12 },
          { num: 8, from: 1, to: 12 },
          { num: 9, from: 1, to: 12 },
          { num: 10, from: 1, to: 12 },
          { num: 11, from: 1, to: 12 },
          { num: 12, from: 1, to: 12 },
          { num: 13, from: 1, to: 12 },
          { num: 14, from: 1, to: 12 },
          { num: 15, from: 1, to: 12 },
          { num: 16, from: 1, to: 12 },
          { num: 17, from: 1, to: 12 },
          { num: 18, from: 1, to: 12 },
          { num: 19, from: 1, to: 12 },
          { num: 20, from: 1, to: 12 },
          { num: 21, from: 1, to: 12 },
          { num: 22, from: 1, to: 12 },
          { num: 23, from: 1, to: 12 },
          { num: 24, from: 1, to: 12 },
          { num: 25, from: 1, to: 12 },
          { num: 26, from: 1, to: 12 },
          { num: 27, from: 1, to: 12 },
          { num: 28, from: 1, to: 12 },
          { num: 29, from: 1, to: 12 },
          { num: 30, from: 1, to: 12 },
        ],
      },
      { extraBed: true, noExtraBed: 15, occA: 45, occC: 0, childs: [] },
    ],
  },
  {
    name: '16 Bed Room',
    options: [
      {
        extraBed: false,
        noExtraBed: 0,
        occA: 32,
        occC: 16,
        childs: [
          { num: 1, from: 1, to: 6 },
          { num: 2, from: 1, to: 6 },
          { num: 3, from: 1, to: 6 },
          { num: 4, from: 1, to: 6 },
          { num: 5, from: 1, to: 6 },
          { num: 6, from: 1, to: 6 },
          { num: 7, from: 1, to: 6 },
          { num: 8, from: 1, to: 6 },
          { num: 9, from: 1, to: 6 },
          { num: 10, from: 1, to: 6 },
          { num: 11, from: 1, to: 6 },
          { num: 12, from: 1, to: 6 },
          { num: 13, from: 1, to: 6 },
          { num: 14, from: 1, to: 6 },
          { num: 15, from: 1, to: 6 },
          { num: 16, from: 1, to: 6 },
        ],
      },
      {
        extraBed: true,
        noExtraBed: 16,
        occA: 32,
        occC: 32,
        childs: [
          { num: 1, from: 1, to: 6 },
          { num: 2, from: 1, to: 6 },
          { num: 3, from: 1, to: 6 },
          { num: 4, from: 1, to: 6 },
          { num: 5, from: 1, to: 6 },
          { num: 6, from: 1, to: 12 },
          { num: 7, from: 1, to: 12 },
          { num: 8, from: 1, to: 12 },
          { num: 9, from: 1, to: 12 },
          { num: 10, from: 1, to: 12 },
          { num: 11, from: 1, to: 12 },
          { num: 12, from: 1, to: 12 },
          { num: 13, from: 1, to: 12 },
          { num: 14, from: 1, to: 12 },
          { num: 15, from: 1, to: 12 },
          { num: 16, from: 1, to: 12 },
          { num: 17, from: 1, to: 12 },
          { num: 18, from: 1, to: 12 },
          { num: 19, from: 1, to: 12 },
          { num: 20, from: 1, to: 12 },
          { num: 21, from: 1, to: 12 },
          { num: 22, from: 1, to: 12 },
          { num: 23, from: 1, to: 12 },
          { num: 24, from: 1, to: 12 },
          { num: 25, from: 1, to: 12 },
          { num: 26, from: 1, to: 12 },
          { num: 27, from: 1, to: 12 },
          { num: 28, from: 1, to: 12 },
          { num: 29, from: 1, to: 12 },
          { num: 30, from: 1, to: 12 },
          { num: 31, from: 1, to: 12 },
          { num: 32, from: 1, to: 12 },
        ],
      },
      { extraBed: true, noExtraBed: 16, occA: 48, occC: 0, childs: [] },
    ],
  },
  {
    name: '17 Bed Room',
    options: [
      {
        extraBed: false,
        noExtraBed: 0,
        occA: 34,
        occC: 17,
        childs: [
          { num: 1, from: 1, to: 6 },
          { num: 2, from: 1, to: 6 },
          { num: 3, from: 1, to: 6 },
          { num: 4, from: 1, to: 6 },
          { num: 5, from: 1, to: 6 },
          { num: 6, from: 1, to: 6 },
          { num: 7, from: 1, to: 6 },
          { num: 8, from: 1, to: 6 },
          { num: 9, from: 1, to: 6 },
          { num: 10, from: 1, to: 6 },
          { num: 11, from: 1, to: 6 },
          { num: 12, from: 1, to: 6 },
          { num: 13, from: 1, to: 6 },
          { num: 14, from: 1, to: 6 },
          { num: 15, from: 1, to: 6 },
          { num: 16, from: 1, to: 6 },
          { num: 17, from: 1, to: 6 },
        ],
      },
      {
        extraBed: true,
        noExtraBed: 17,
        occA: 34,
        occC: 34,
        childs: [
          { num: 1, from: 1, to: 6 },
          { num: 2, from: 1, to: 6 },
          { num: 3, from: 1, to: 6 },
          { num: 4, from: 1, to: 6 },
          { num: 5, from: 1, to: 6 },
          { num: 6, from: 1, to: 12 },
          { num: 7, from: 1, to: 12 },
          { num: 8, from: 1, to: 12 },
          { num: 9, from: 1, to: 12 },
          { num: 10, from: 1, to: 12 },
          { num: 11, from: 1, to: 12 },
          { num: 12, from: 1, to: 12 },
          { num: 13, from: 1, to: 12 },
          { num: 14, from: 1, to: 12 },
          { num: 15, from: 1, to: 12 },
          { num: 16, from: 1, to: 12 },
          { num: 17, from: 1, to: 12 },
          { num: 18, from: 1, to: 12 },
          { num: 19, from: 1, to: 12 },
          { num: 20, from: 1, to: 12 },
          { num: 21, from: 1, to: 12 },
          { num: 22, from: 1, to: 12 },
          { num: 23, from: 1, to: 12 },
          { num: 24, from: 1, to: 12 },
          { num: 25, from: 1, to: 12 },
          { num: 26, from: 1, to: 12 },
          { num: 27, from: 1, to: 12 },
          { num: 28, from: 1, to: 12 },
          { num: 29, from: 1, to: 12 },
          { num: 30, from: 1, to: 12 },
          { num: 31, from: 1, to: 12 },
          { num: 32, from: 1, to: 12 },
          { num: 33, from: 1, to: 12 },
          { num: 34, from: 1, to: 12 },
        ],
      },
      { extraBed: true, noExtraBed: 17, occA: 51, occC: 0, childs: [] },
    ],
  },
  {
    name: '18 Bed Room',
    options: [
      {
        extraBed: false,
        noExtraBed: 0,
        occA: 36,
        occC: 18,
        childs: [
          { num: 1, from: 1, to: 6 },
          { num: 2, from: 1, to: 6 },
          { num: 3, from: 1, to: 6 },
          { num: 4, from: 1, to: 6 },
          { num: 5, from: 1, to: 6 },
          { num: 6, from: 1, to: 6 },
          { num: 7, from: 1, to: 6 },
          { num: 8, from: 1, to: 6 },
          { num: 9, from: 1, to: 6 },
          { num: 10, from: 1, to: 6 },
          { num: 11, from: 1, to: 6 },
          { num: 12, from: 1, to: 6 },
          { num: 13, from: 1, to: 6 },
          { num: 14, from: 1, to: 6 },
          { num: 15, from: 1, to: 6 },
          { num: 16, from: 1, to: 6 },
          { num: 17, from: 1, to: 6 },
          { num: 18, from: 1, to: 6 },
        ],
      },
      {
        extraBed: true,
        noExtraBed: 18,
        occA: 36,
        occC: 36,
        childs: [
          { num: 1, from: 1, to: 6 },
          { num: 2, from: 1, to: 6 },
          { num: 3, from: 1, to: 6 },
          { num: 4, from: 1, to: 6 },
          { num: 5, from: 1, to: 6 },
          { num: 6, from: 1, to: 12 },
          { num: 7, from: 1, to: 12 },
          { num: 8, from: 1, to: 12 },
          { num: 9, from: 1, to: 12 },
          { num: 10, from: 1, to: 12 },
          { num: 11, from: 1, to: 12 },
          { num: 12, from: 1, to: 12 },
          { num: 13, from: 1, to: 12 },
          { num: 14, from: 1, to: 12 },
          { num: 15, from: 1, to: 12 },
          { num: 16, from: 1, to: 12 },
          { num: 17, from: 1, to: 12 },
          { num: 18, from: 1, to: 12 },
          { num: 19, from: 1, to: 12 },
          { num: 20, from: 1, to: 12 },
          { num: 21, from: 1, to: 12 },
          { num: 22, from: 1, to: 12 },
          { num: 23, from: 1, to: 12 },
          { num: 24, from: 1, to: 12 },
          { num: 25, from: 1, to: 12 },
          { num: 26, from: 1, to: 12 },
          { num: 27, from: 1, to: 12 },
          { num: 28, from: 1, to: 12 },
          { num: 29, from: 1, to: 12 },
          { num: 30, from: 1, to: 12 },
          { num: 31, from: 1, to: 12 },
          { num: 32, from: 1, to: 12 },
          { num: 33, from: 1, to: 12 },
          { num: 34, from: 1, to: 12 },
          { num: 35, from: 1, to: 12 },
          { num: 36, from: 1, to: 12 },
        ],
      },
      { extraBed: true, noExtraBed: 18, occA: 54, occC: 0, childs: [] },
    ],
  },
  {
    name: '19 Bed Room',
    options: [
      {
        extraBed: false,
        noExtraBed: 0,
        occA: 38,
        occC: 19,
        childs: [
          { num: 1, from: 1, to: 6 },
          { num: 2, from: 1, to: 6 },
          { num: 3, from: 1, to: 6 },
          { num: 4, from: 1, to: 6 },
          { num: 5, from: 1, to: 6 },
          { num: 6, from: 1, to: 6 },
          { num: 7, from: 1, to: 6 },
          { num: 8, from: 1, to: 6 },
          { num: 9, from: 1, to: 6 },
          { num: 10, from: 1, to: 6 },
          { num: 11, from: 1, to: 6 },
          { num: 12, from: 1, to: 6 },
          { num: 13, from: 1, to: 6 },
          { num: 14, from: 1, to: 6 },
          { num: 15, from: 1, to: 6 },
          { num: 16, from: 1, to: 6 },
          { num: 17, from: 1, to: 6 },
          { num: 18, from: 1, to: 6 },
          { num: 19, from: 1, to: 6 },
        ],
      },
      {
        extraBed: true,
        noExtraBed: 19,
        occA: 38,
        occC: 38,
        childs: [
          { num: 1, from: 1, to: 6 },
          { num: 2, from: 1, to: 6 },
          { num: 3, from: 1, to: 6 },
          { num: 4, from: 1, to: 6 },
          { num: 5, from: 1, to: 6 },
          { num: 6, from: 1, to: 12 },
          { num: 7, from: 1, to: 12 },
          { num: 8, from: 1, to: 12 },
          { num: 9, from: 1, to: 12 },
          { num: 10, from: 1, to: 12 },
          { num: 11, from: 1, to: 12 },
          { num: 12, from: 1, to: 12 },
          { num: 13, from: 1, to: 12 },
          { num: 14, from: 1, to: 12 },
          { num: 15, from: 1, to: 12 },
          { num: 16, from: 1, to: 12 },
          { num: 17, from: 1, to: 12 },
          { num: 18, from: 1, to: 12 },
          { num: 19, from: 1, to: 12 },
          { num: 20, from: 1, to: 12 },
          { num: 21, from: 1, to: 12 },
          { num: 22, from: 1, to: 12 },
          { num: 23, from: 1, to: 12 },
          { num: 24, from: 1, to: 12 },
          { num: 25, from: 1, to: 12 },
          { num: 26, from: 1, to: 12 },
          { num: 27, from: 1, to: 12 },
          { num: 28, from: 1, to: 12 },
          { num: 29, from: 1, to: 12 },
          { num: 30, from: 1, to: 12 },
          { num: 31, from: 1, to: 12 },
          { num: 32, from: 1, to: 12 },
          { num: 33, from: 1, to: 12 },
          { num: 34, from: 1, to: 12 },
          { num: 35, from: 1, to: 12 },
          { num: 36, from: 1, to: 12 },
          { num: 37, from: 1, to: 12 },
          { num: 38, from: 1, to: 12 },
        ],
      },
      { extraBed: true, noExtraBed: 19, occA: 57, occC: 0, childs: [] },
    ],
  },
  {
    name: '20 Bed Room',
    options: [
      {
        extraBed: false,
        noExtraBed: 0,
        occA: 40,
        occC: 20,
        childs: [
          { num: 1, from: 1, to: 6 },
          { num: 2, from: 1, to: 6 },
          { num: 3, from: 1, to: 6 },
          { num: 4, from: 1, to: 6 },
          { num: 5, from: 1, to: 6 },
          { num: 6, from: 1, to: 6 },
          { num: 7, from: 1, to: 6 },
          { num: 8, from: 1, to: 6 },
          { num: 9, from: 1, to: 6 },
          { num: 10, from: 1, to: 6 },
          { num: 11, from: 1, to: 6 },
          { num: 12, from: 1, to: 6 },
          { num: 13, from: 1, to: 6 },
          { num: 14, from: 1, to: 6 },
          { num: 15, from: 1, to: 6 },
          { num: 16, from: 1, to: 6 },
          { num: 17, from: 1, to: 6 },
          { num: 18, from: 1, to: 6 },
          { num: 19, from: 1, to: 6 },
          { num: 20, from: 1, to: 6 },
        ],
      },
      {
        extraBed: true,
        noExtraBed: 20,
        occA: 40,
        occC: 40,
        childs: [
          { num: 1, from: 1, to: 6 },
          { num: 2, from: 1, to: 6 },
          { num: 3, from: 1, to: 6 },
          { num: 4, from: 1, to: 6 },
          { num: 5, from: 1, to: 6 },
          { num: 6, from: 1, to: 12 },
          { num: 7, from: 1, to: 12 },
          { num: 8, from: 1, to: 12 },
          { num: 9, from: 1, to: 12 },
          { num: 10, from: 1, to: 12 },
          { num: 11, from: 1, to: 12 },
          { num: 12, from: 1, to: 12 },
          { num: 13, from: 1, to: 12 },
          { num: 14, from: 1, to: 12 },
          { num: 15, from: 1, to: 12 },
          { num: 16, from: 1, to: 12 },
          { num: 17, from: 1, to: 12 },
          { num: 18, from: 1, to: 12 },
          { num: 19, from: 1, to: 12 },
          { num: 20, from: 1, to: 12 },
          { num: 21, from: 1, to: 12 },
          { num: 22, from: 1, to: 12 },
          { num: 23, from: 1, to: 12 },
          { num: 24, from: 1, to: 12 },
          { num: 25, from: 1, to: 12 },
          { num: 26, from: 1, to: 12 },
          { num: 27, from: 1, to: 12 },
          { num: 28, from: 1, to: 12 },
          { num: 29, from: 1, to: 12 },
          { num: 30, from: 1, to: 12 },
          { num: 31, from: 1, to: 12 },
          { num: 32, from: 1, to: 12 },
          { num: 33, from: 1, to: 12 },
          { num: 34, from: 1, to: 12 },
          { num: 35, from: 1, to: 12 },
          { num: 36, from: 1, to: 12 },
          { num: 37, from: 1, to: 12 },
          { num: 38, from: 1, to: 12 },
          { num: 39, from: 1, to: 12 },
          { num: 40, from: 1, to: 12 },
        ],
      },
      { extraBed: true, noExtraBed: 20, occA: 60, occC: 0, childs: [] },
    ],
  },
];
export const menuAction: any = [
  {
    name: 'Booking',
    target: '_blank',
    admin: false,
    url: 'configuration/report-booking',
  },
];

export const bedTypes: any = ['Single Bed', 'Extra Bed(A)', 'Extra Bed(C)', 'Additional Person'];
export const listTypeBed: any = [
  {
    name: 'Double Bed',
    occ: 2,
    displayName: 'Double Bed',
  },
  {
    name: 'Twin Bed',
    occ: 2,
    displayName: 'Twin Bed',
  },
  {
    name: 'Triple Bed (Share room + Extra Bed)',
    occ: 3,
    unCheckOcc: true,
    displayName: 'Triple Bed (Share room + Extra Bed)',
  },
  {
    name: 'Triple Bed',
    occ: 3,
    displayName: 'Triple Bed',
  },
  {
    name: 'Single Bed',
    occ: 1,
    displayName: 'Single Bed',
  },
  {
    name: 'Extra Bed (A)',
    occ: 1,
    displayName: 'Extra Bed (A)',
  },
  {
    name: 'Extra Bed (C)',
    occ: 1,
    displayName: 'Extra Bed (C)',
  },
  {
    name: 'Additional Person',
    occ: 1,
    displayName: 'Additional Person',
  },
  {
    name: 'Child Sharing',
    occ: 1,
    displayName: 'CHILD SHARING',
    isChildSharing: true,
  },
  {
    name: '2 Bedroom',
    occ: 4,
    displayName: '2 Bedroom',
  },
  {
    name: '3 Bedroom',
    occ: 6,
    displayName: '3 Bedroom',
  },
  {
    name: '4 Bedroom',
    occ: 8,
    displayName: '4 Bedroom',
  },
  {
    name: '5 Bedroom',
    occ: 10,
    displayName: '5 Bedroom',
  },
  {
    name: 'Blank',
    occ: 0,
    displayName: 'Blank',
  },
];
// listTypeBedConfigAC
export const listTypeBedConfigAC: any = [
  {
    name: 'Double Bed',
    occ: 2,
    displayName: 'DBL',
  },
  {
    name: 'Twin Bed',
    occ: 2,
    displayName: 'TWN',
  },
  {
    name: 'KING',
    occ: 2,
    displayName: 'KING',
  },
  {
    name: 'Triple Bed (Share room + Extra Bed)',
    occ: 3,
    unCheckOcc: true,
    displayName: 'TWN + EB',
  },
  {
    name: 'Triple Bed',
    occ: 3,
    displayName: 'TPL',
  },
  {
    name: 'Single Bed',
    occ: 1,
    displayName: 'SGL',
  },
  {
    name: 'Extra Bed (A)',
    occ: 1,
    displayName: 'EB (A)',
  },
  {
    name: 'Extra Bed (C)',
    occ: 1,
    displayName: 'EB (C)',
  },
  {
    name: 'Child Sharing',
    occ: 1,
    displayName: 'CHILD SHARING',
    isChildSharing: true,
  },
  {
    name: 'Additional Person',
    occ: 1,
    displayName: 'Additional Pax',
  },
  {
    name: '2 Bedroom',
    occ: 4,
    displayName: '2 BR',
  },
  {
    name: '3 Bedroom',
    occ: 6,
    displayName: '3 BR',
  },
  {
    name: '4 Bedroom',
    occ: 8,
    displayName: '4 BR',
  },
  {
    name: '5 Bedroom',
    occ: 10,
    displayName: '5 BR',
  },

  {
    name: '1 BR',
    occ: 2,
    displayName: '1 BR',
  },
  {
    name: '6 BR',
    occ: 12,
    displayName: '6 BR',
  },
  {
    name: '7 BR',
    occ: 14,
    displayName: '7 BR',
  },
  {
    name: '8 BR',
    occ: 16,
    displayName: '8 BR',
  },
  {
    name: '9 BR',
    occ: 18,
    displayName: '9 BR',
  },
  {
    name: '10 BR',
    occ: 20,
    displayName: '10 BR',
  },
  {
    name: '11 BR',
    occ: 22,
    displayName: '11 BR',
  },
  {
    name: '12 BR',
    occ: 24,
    displayName: '12 BR',
  },
  {
    name: '1 CB',
    occ: 2,
    displayName: '1 CB',
  },
  {
    name: '2 CB',
    occ: 4,
    displayName: '2 CB',
  },
  {
    name: '3 CB',
    occ: 6,
    displayName: '3 CB',
  },
  {
    name: '4 CB',
    occ: 8,
    displayName: '4 CB',
  },
  {
    name: '5 CB',
    occ: 10,
    displayName: '5 CB',
  },
  {
    name: '6 CB',
    occ: 12,
    displayName: '6 CB',
  },
  {
    name: '7 CB',
    occ: 14,
    displayName: '7 CB',
  },
  {
    name: '8 CB',
    occ: 16,
    displayName: '8 CB',
  },
  {
    name: '9 CB',
    occ: 18,
    displayName: '9 CB',
  },
  {
    name: '10 CB',
    occ: 20,
    displayName: '10 CB',
  },
  {
    name: '11 CB',
    occ: 22,
    displayName: '11 CB',
  },
  {
    name: '12 CB',
    occ: 24,
    displayName: '12 CB',
  },
  {
    name: 'Blank',
    occ: 0,
    displayName: 'Blank',
  },
];

export const menuSetting: any = [
  // {
  //   name: 'Outgoing Mailbox',
  //   icon: 'bi bi-mailbox',
  //   target: '_blank',
  //   admin: false,
  //   product: false,
  //   url: 'configuration/outgoing-mailbox',
  // },
  {
    name: 'Outgoing Mailbox',
    icon: 'bi bi-mailbox',
    target: '_blank',
    admin: false,
    product: false,
    url: 'configuration/outgoing-mailbox',
  },
];

export const menuUsers: any = [
  {
    name: 'AI Management',
    icon: 'bi bi-robot',
    target: '_blank',
    admin: true,
    product: false,
    supplerAdmin: true,
    url: 'configuration/ai-management',
  },
];
export const banks: any = [
  {
    nation: 'vn',
    name: 'Vietnam',
  },
  {
    nation: 'vn',
    name: 'Hongkong',
  },
];

export const lsruletype: any = [
  {
    _type: 1,
    name: 'Allocation Restrictions',
  },
  {
    _type: 2,
    name: 'Booking Restrictions',
  },
  {
    _type: 3,
    name: 'Minimum Age',
  },
  {
    _type: 4,
    name: 'Minimum Stays',
  },
  {
    _type: 5,
    name: 'Special Offers',
    default: true,
  },
];
export const array_Pass_Option_2 = [
  { key: 1, name: 'Night/Day' },
  { key: 2, name: 'Passenger' },
  { key: 3, name: 'Per Booked Service' },
  { key: 4, name: 'Per Unit' },
  { key: 5, name: 'Unit' },
  { key: 6, name: 'Room' },
];

export const AgencyTypes = [
  // { value: 'Wholesale', name: 'Wholesales' }, // Wholesale & Tour Operators
  // { value: 'Retail', name: 'Leisure' }, // Leisure & Retail
  // { value: 'US retail', name: 'US Retails' }, // US Retail
  // { value: 'M.I.C.E', name: 'Meetings and Events (M&I)' }, // Events
  // { value: 'Cruise Ship', name: 'Cruise Ship' }, // Cruise
  // { value: 'Direct', name: 'Direct' }, // Direct Booking

  { value: 'Wholesale', name: 'Wholesale & Tour Operators' }, // Wholesale & Tour Operators
  { value: 'Retail', name: 'Leisure & Retail' }, // Leisure & Retail
  { value: 'US retail', name: 'US Retail' }, // US Retail
  { value: 'M.I.C.E', name: 'Events' }, // Events
  { value: 'Cruise Ship', name: 'Cruise' }, // Cruise
  { value: 'Direct', name: 'Direct Booking' }, // Direct Booking
  { value: 'TA', name: 'TA' },
];
export const array_Pass_Option_3 = [
  { key: 1, name: 'Free' },
  { key: 2, name: 'Reduce By %' },
  { key: 3, name: 'Reduce By Amount' },
  { key: 4, name: 'Supplement %' },
  { key: 5, name: 'Supplement Amount' },
  { key: 6, name: 'Fixed Rate' },
  { key: 7, name: 'Surcharge' },
];
export const array_Pass_Option_4 = [
  { key: 1, name: 'Per Person' },
  { key: 2, name: 'Per Unit' },
  { key: 3, name: 'Prev. Functionality' },
];
export const lsItemsOptionalSelect: any = [
  { name: 'Extra Bed (A)', key: 'Extra Bed A', quantity: 0, selected: false },
  { name: 'Extra Bed (C)', key: 'Extra Bed C', quantity: 0, selected: false },
  {
    name: 'Breakfast Child',
    key: 'Breakfast Child',
    quantity: 0,
    selected: false,
  },
  {
    name: 'Breakfast Adult',
    key: 'Breakfast Adult',
    quantity: 0,
    selected: false,
  },
  {
    name: 'Additional Person',
    key: 'Additional Person',
    quantity: 0,
    selected: false,
  },
  { name: 'Child Sharing', key: 'Child Sharing', quantity: 0, selected: false },
  {
    name: 'Late check-out',
    key: 'Late check-out',
    quantity: 0,
    selected: false,
  },
  {
    name: 'Early check-in',
    key: 'Early check-in',
    quantity: 0,
    selected: false,
  },
];
export const languages = ['en-US', 'es-ES'];
export const defaultLanguage = languages[0];
export const nationality: any = [
  {
    code: 'WW',
    name: 'Worldwide',
  },
  {
    code: 'MC',
    name: 'Multi-country',
  },
  {
    code: 'AF',
    name: 'Afghanistan',
  },
  {
    code: 'AL',
    name: 'Albania',
  },
  {
    code: 'DZ',
    name: 'Algeria',
  },
  {
    code: 'AS',
    name: 'American Samoa',
  },
  {
    code: 'AD',
    name: 'Andorre',
  },
  {
    code: 'AO',
    name: 'Angola',
  },
  {
    code: 'AI',
    name: 'Anguilla',
  },
  {
    code: 'AQ',
    name: 'Antarctica',
  },
  {
    code: 'AG',
    name: 'Antigua and Barbuda',
  },
  {
    code: 'AR',
    name: 'Argentina',
  },
  {
    code: 'AM',
    name: 'Armenia',
  },
  {
    code: 'AW',
    name: 'Aruba',
  },
  {
    code: 'AU',
    name: 'Australia',
  },
  {
    code: 'AT',
    name: 'Austria',
  },
  {
    code: 'AZ',
    name: 'Azerbaijan',
  },
  {
    code: 'BS',
    name: 'Bahamas',
  },
  {
    code: 'BH',
    name: 'Bahrain',
  },
  {
    code: 'BD',
    name: 'Bangladesh',
  },
  {
    code: 'BB',
    name: 'Barbade',
  },
  {
    code: 'BY',
    name: 'Belarus',
  },
  {
    code: 'BE',
    name: 'Belgium',
  },
  {
    code: 'BZ',
    name: 'Belize',
  },
  {
    code: 'BJ',
    name: 'Benin',
  },
  {
    code: 'BM',
    name: 'Bermuda',
  },
  {
    code: 'BT',
    name: 'Bhutan',
  },
  {
    code: 'BO',
    name: 'Bolivia',
  },
  {
    code: 'BQ',
    name: 'Bonaire, Sint Eustatius and Saba',
  },
  {
    code: 'BA',
    name: 'Bosnia and Herzegovina',
  },
  {
    code: 'BW',
    name: 'Botswana',
  },
  {
    code: 'BV',
    name: 'Bouvet Island',
  },
  {
    code: 'BR',
    name: 'Brazil',
  },
  {
    code: 'IO',
    name: 'British Indian Ocean Territory',
  },
  {
    code: 'VG',
    name: 'British Virgin Islands',
  },
  {
    code: 'BN',
    name: 'Brunei',
  },
  {
    code: 'BG',
    name: 'Bulgaria',
  },
  {
    code: 'BF',
    name: 'Burkina Faso',
  },
  {
    code: 'BI',
    name: 'Burundi',
  },
  {
    code: 'KH',
    name: 'Cambodia',
  },
  {
    code: 'CM',
    name: 'Cameroon',
  },
  {
    code: 'CA',
    name: 'Canada',
  },
  {
    code: 'CV',
    name: 'Cape Verde',
  },
  {
    code: 'KY',
    name: 'Cayman Islands',
  },
  {
    code: 'CF',
    name: 'Central African Republic',
  },
  {
    code: 'TD',
    name: 'Chad',
  },
  {
    code: 'CL',
    name: 'Chile',
  },
  {
    code: 'CN',
    name: 'China',
  },
  {
    code: 'CX',
    name: 'Christmas Island',
  },
  {
    code: 'CC',
    name: 'Cocos (Keeling) Islands',
  },
  {
    code: 'CO',
    name: 'Colombia',
  },
  {
    code: 'KM',
    name: 'Comoros',
  },
  {
    code: 'CG',
    name: 'Congo',
  },
  {
    code: 'CD',
    name: 'Congo (Dem. Rep.)',
  },
  {
    code: 'CK',
    name: 'Cook Islands',
  },
  {
    code: 'CR',
    name: 'Costa Rica',
  },
  {
    code: 'ME',
    name: 'Crna Gora',
  },
  {
    code: 'HR',
    name: 'Croatia',
  },
  {
    code: 'CU',
    name: 'Cuba',
  },
  {
    code: 'CW',
    name: 'Curaçao',
  },
  {
    code: 'CY',
    name: 'Cyprus',
  },
  {
    code: 'CZ',
    name: 'Czech Republic',
  },
  {
    code: 'CI',
    name: "Côte D'Ivoire",
  },
  {
    code: 'DK',
    name: 'Denmark',
  },
  {
    code: 'DJ',
    name: 'Djibouti',
  },
  {
    code: 'DM',
    name: 'Dominica',
  },
  {
    code: 'DO',
    name: 'Dominican Republic',
  },
  {
    code: 'TL',
    name: 'East Timor',
  },
  {
    code: 'EC',
    name: 'Ecuador',
  },
  {
    code: 'EG',
    name: 'Egypt',
  },
  {
    code: 'SV',
    name: 'El Salvador',
  },
  {
    code: 'GQ',
    name: 'Equatorial Guinea',
  },
  {
    code: 'ER',
    name: 'Eritrea',
  },
  {
    code: 'EE',
    name: 'Estonia',
  },
  {
    code: 'ET',
    name: 'Ethiopia',
  },
  {
    code: 'FK',
    name: 'Falkland Islands',
  },
  {
    code: 'FO',
    name: 'Faroe Islands',
  },
  {
    code: 'FJ',
    name: 'Fiji',
  },
  {
    code: 'FI',
    name: 'Finland',
  },
  {
    code: 'FR',
    name: 'France',
  },
  {
    code: 'GF',
    name: 'French Guiana',
  },
  {
    code: 'PF',
    name: 'French Polynesia',
  },
  {
    code: 'TF',
    name: 'French Southern Territories',
  },
  {
    code: 'GA',
    name: 'Gabon',
  },
  {
    code: 'GM',
    name: 'Gambia',
  },
  {
    code: 'GE',
    name: 'Georgia',
  },
  {
    code: 'DE',
    name: 'Germany',
  },
  {
    code: 'GH',
    name: 'Ghana',
  },
  {
    code: 'GI',
    name: 'Gibraltar',
  },
  {
    code: 'GR',
    name: 'Greece',
  },
  {
    code: 'GL',
    name: 'Greenland',
  },
  {
    code: 'GD',
    name: 'Grenada',
  },
  {
    code: 'GP',
    name: 'Guadeloupe',
  },
  {
    code: 'GU',
    name: 'Guam',
  },
  {
    code: 'GT',
    name: 'Guatemala',
  },
  {
    code: 'GG',
    name: 'Guernsey and Alderney',
  },
  {
    code: 'GN',
    name: 'Guinea',
  },
  {
    code: 'GW',
    name: 'Guinea-Bissau',
  },
  {
    code: 'GY',
    name: 'Guyana',
  },
  {
    code: 'HT',
    name: 'Haiti',
  },
  {
    code: 'HM',
    name: 'Heard and McDonald Islands',
  },
  {
    code: 'HN',
    name: 'Honduras',
  },
  {
    code: 'HK',
    name: 'Hong Kong',
  },
  {
    code: 'HU',
    name: 'Hungary',
  },
  {
    code: 'IS',
    name: 'Iceland',
  },
  {
    code: 'IN',
    name: 'India',
  },
  {
    code: 'ID',
    name: 'Indonesia',
  },
  {
    code: 'IR',
    name: 'Iran',
  },
  {
    code: 'IQ',
    name: 'Iraq',
  },
  {
    code: 'IE',
    name: 'Ireland',
  },
  {
    code: 'IM',
    name: 'Isle of Man',
  },
  {
    code: 'IL',
    name: 'Israel',
  },
  {
    code: 'IT',
    name: 'Italy',
  },
  {
    code: 'JM',
    name: 'Jamaica',
  },
  {
    code: 'JP',
    name: 'Japan',
  },
  {
    code: 'JE',
    name: 'Jersey',
  },
  {
    code: 'JO',
    name: 'Jordan',
  },
  {
    code: 'KZ',
    name: 'Kazakhstan',
  },
  {
    code: 'KE',
    name: 'Kenya',
  },
  {
    code: 'KI',
    name: 'Kiribati',
  },
  {
    code: 'KP',
    name: 'Korea (North)',
  },
  {
    code: 'KR',
    name: 'Korea (South)',
  },
  {
    code: 'KW',
    name: 'Kuwait',
  },
  {
    code: 'KG',
    name: 'Kyrgyzstan',
  },
  {
    code: 'LA',
    name: 'Laos',
  },
  {
    code: 'LV',
    name: 'Latvia',
  },
  {
    code: 'LB',
    name: 'Lebanon',
  },
  {
    code: 'LS',
    name: 'Lesotho',
  },
  {
    code: 'LR',
    name: 'Liberia',
  },
  {
    code: 'LY',
    name: 'Libya',
  },
  {
    code: 'LI',
    name: 'Liechtenstein',
  },
  {
    code: 'LT',
    name: 'Lithuania',
  },
  {
    code: 'LU',
    name: 'Luxembourg',
  },
  {
    code: 'MO',
    name: 'Macao',
  },
  {
    code: 'MK',
    name: 'Macedonia',
  },
  {
    code: 'MG',
    name: 'Madagascar',
  },
  {
    code: 'MW',
    name: 'Malawi',
  },
  {
    code: 'MY',
    name: 'Malaysia',
  },
  {
    code: 'MV',
    name: 'Maldives',
  },
  {
    code: 'ML',
    name: 'Mali',
  },
  {
    code: 'MT',
    name: 'Malta',
  },
  {
    code: 'MH',
    name: 'Marshall Islands',
  },
  {
    code: 'MQ',
    name: 'Martinique',
  },
  {
    code: 'MR',
    name: 'Mauritania',
  },
  {
    code: 'MU',
    name: 'Mauritius',
  },
  {
    code: 'YT',
    name: 'Mayotte',
  },
  {
    code: 'MX',
    name: 'Mexico',
  },
  {
    code: 'FM',
    name: 'Micronesia',
  },
  {
    code: 'MD',
    name: 'Moldova',
  },
  {
    code: 'MC',
    name: 'Monaco',
  },
  {
    code: 'MN',
    name: 'Mongolia',
  },
  {
    code: 'MS',
    name: 'Montserrat',
  },
  {
    code: 'MA',
    name: 'Morocco',
  },
  {
    code: 'MZ',
    name: 'Mozambique',
  },
  {
    code: 'MM',
    name: 'Myanmar',
  },
  {
    code: 'NA',
    name: 'Namibia',
  },
  {
    code: 'NR',
    name: 'Nauru',
  },
  {
    code: 'NP',
    name: 'Nepal',
  },
  {
    code: 'NL',
    name: 'Netherlands',
  },
  {
    code: 'AN',
    name: 'Netherlands Antilles',
  },
  {
    code: 'NC',
    name: 'New Caledonia',
  },
  {
    code: 'NZ',
    name: 'New Zealand',
  },
  {
    code: 'NI',
    name: 'Nicaragua',
  },
  {
    code: 'NE',
    name: 'Niger',
  },
  {
    code: 'NG',
    name: 'Nigeria',
  },
  {
    code: 'NU',
    name: 'Niue',
  },
  {
    code: 'NF',
    name: 'Norfolk Island',
  },
  {
    code: 'MP',
    name: 'Northern Mariana Islands',
  },
  {
    code: 'NO',
    name: 'Norway',
  },
  {
    code: 'OM',
    name: 'Oman',
  },
  {
    code: 'PK',
    name: 'Pakistan',
  },
  {
    code: 'PW',
    name: 'Palau',
  },
  {
    code: 'PS',
    name: 'Palestine',
  },
  {
    code: 'PA',
    name: 'Panama',
  },
  {
    code: 'PG',
    name: 'Papua New Guinea',
  },
  {
    code: 'PY',
    name: 'Paraguay',
  },
  {
    code: 'PE',
    name: 'Peru',
  },
  {
    code: 'PH',
    name: 'Philippines',
  },
  {
    code: 'PN',
    name: 'Pitcairn',
  },
  {
    code: 'PL',
    name: 'Poland',
  },
  {
    code: 'PT',
    name: 'Portugal',
  },
  {
    code: 'PR',
    name: 'Puerto Rico',
  },
  {
    code: 'QA',
    name: 'Qatar',
  },
  {
    code: 'RO',
    name: 'Romania',
  },
  {
    code: 'RU',
    name: 'Russia',
  },
  {
    code: 'RW',
    name: 'Rwanda',
  },
  {
    code: 'RE',
    name: 'Réunion',
  },
  {
    code: 'BL',
    name: 'Saint Barthélemy',
  },
  {
    code: 'SH',
    name: 'Saint Helena',
  },
  {
    code: 'KN',
    name: 'Saint Kitts and Nevis',
  },
  {
    code: 'LC',
    name: 'Saint Lucia',
  },
  {
    code: 'MF',
    name: 'Saint Martin',
  },
  {
    code: 'PM',
    name: 'Saint Pierre and Miquelon',
  },
  {
    code: 'VC',
    name: 'Saint Vincent and the Grenadines',
  },
  {
    code: 'WS',
    name: 'Samoa',
  },
  {
    code: 'SM',
    name: 'San Marino',
  },
  {
    code: 'SA',
    name: 'Saudi Arabia',
  },
  {
    code: 'SN',
    name: 'Senegal',
  },
  {
    code: 'RS',
    name: 'Serbia',
  },
  {
    code: 'SC',
    name: 'Seychelles',
  },
  {
    code: 'SL',
    name: 'Sierra Leone',
  },
  {
    code: 'SG',
    name: 'Singapore',
  },
  {
    code: 'SX',
    name: 'Sint Maarten',
  },
  {
    code: 'SK',
    name: 'Slovakia',
  },
  {
    code: 'SI',
    name: 'Slovenia',
  },
  {
    code: 'SB',
    name: 'Solomon Islands',
  },
  {
    code: 'SO',
    name: 'Somalia',
  },
  {
    code: 'ZA',
    name: 'South Africa',
  },
  {
    code: 'GS',
    name: 'South Georgia and the South Sandwich Islands',
  },
  {
    code: 'SS',
    name: 'South Sudan',
  },
  {
    code: 'ES',
    name: 'Spain',
  },
  {
    code: 'LK',
    name: 'Sri Lanka',
  },
  {
    code: 'SD',
    name: 'Sudan',
  },
  {
    code: 'SR',
    name: 'Suriname',
  },
  {
    code: 'SJ',
    name: 'Svalbard and Jan Mayen',
  },
  {
    code: 'SZ',
    name: 'Swaziland',
  },
  {
    code: 'SE',
    name: 'Sweden',
  },
  {
    code: 'CH',
    name: 'Switzerland',
  },
  {
    code: 'SY',
    name: 'Syria',
  },
  {
    code: 'ST',
    name: 'São Tomé and Príncipe',
  },
  {
    code: 'TW',
    name: 'Taiwan',
  },
  {
    code: 'TJ',
    name: 'Tajikistan',
  },
  {
    code: 'TZ',
    name: 'Tanzania',
  },
  {
    code: 'TH',
    name: 'Thailand',
  },
  {
    code: 'TG',
    name: 'Togo',
  },
  {
    code: 'TK',
    name: 'Tokelau',
  },
  {
    code: 'TO',
    name: 'Tonga',
  },
  {
    code: 'TT',
    name: 'Trinidad and Tobago',
  },
  {
    code: 'TN',
    name: 'Tunisia',
  },
  {
    code: 'TR',
    name: 'Turkey',
  },
  {
    code: 'TM',
    name: 'Turkmenistan',
  },
  {
    code: 'TC',
    name: 'Turks and Caicos Islands',
  },
  {
    code: 'TV',
    name: 'Tuvalu',
  },
  {
    code: 'UG',
    name: 'Uganda',
  },
  {
    code: 'UA',
    name: 'Ukraine',
  },
  {
    code: 'AE',
    name: 'United Arab Emirates',
  },
  {
    code: 'GB',
    name: 'United Kingdom',
  },
  {
    code: 'UM',
    name: 'United States Minor Outlying Islands',
  },
  {
    code: 'US',
    name: 'United States of America',
  },
  {
    code: 'UY',
    name: 'Uruguay',
  },
  {
    code: 'UZ',
    name: 'Uzbekistan',
  },
  {
    code: 'VU',
    name: 'Vanuatu',
  },
  {
    code: 'VA',
    name: 'Vatican City',
  },
  {
    code: 'VE',
    name: 'Venezuela',
  },
  {
    code: 'VN',
    name: 'Vietnam',
  },
  {
    code: 'VI',
    name: 'Virgin Islands of the United States',
  },
  {
    code: 'WF',
    name: 'Wallis and Futuna',
  },
  {
    code: 'EH',
    name: 'Western Sahara',
  },
  {
    code: 'YE',
    name: 'Yemen',
  },
  {
    code: 'ZM',
    name: 'Zambia',
  },
  {
    code: 'ZW',
    name: 'Zimbabwe',
  },
];
